export const types = {
  IUserRepository: Symbol("IUserRepository"),
  IUserService: Symbol("IUserService"),
  IDatabase: Symbol("IDatabase"),
  IRegisterUserRepository: Symbol("IRegisterUserRepository"),
  IRegisterUserService: Symbol("IRegisterUserService"),
  IDocumentRepository: Symbol("IDocumentRepository"),
  IDocumentService: Symbol("IDocumentService"),
  IVendorRepository: Symbol("IVendorRepository"),
  IVendorService: Symbol("IVendorService"),
  IRoleRepository: Symbol("IRoleRepository"),
  IRoleService: Symbol("IRoleService"),
  IVendorUserRepository: Symbol("IVendorUserRepository"),
  IVendorUserService: Symbol("IVendorUserService"),
  ICountryRepository: Symbol("ICountryRepository"),
  ICountryService: Symbol("ICountryService"),
  IUserRoleRepository: Symbol("IUserRoleRepository"),
  IUserRoleService: Symbol("IUserRoleService"),
};
